language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
script: npm run test-coverage
after_script: npm run test-coverage && cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: mugo@forfuture.co.ke
  api_key:
    secure: CSPz2DDN3zgBS+sg9Y05sO/TUe19aJqFtcQ+sIHoy5qAQ6axsp4ZqX6m4t9dBq+zUIWijxhK71VxPEJv4nJCCJ0N4t2VokBfBWYZXb7kn3LlK+Pc524mW3IMVoQ7ULk72ffasTnlq/pYcz6iE1HF028krR+Ld0FaXFiRlDnPGwM=
  on:
    tags: true
    repo: docvy/utils
    branch: master
